### ISSUE TITLE
Panic when scrolling down one line while tailing the log

### ISSUE THREAD

**Issue by uaraven** [uaraven/logview#3]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x13a62cc]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc00022e000)
	/Users/ovoronin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210217110421-8a8f78a6dd01/application.go:243 +0x87
panic(0x14858e0, 0x17e8f30)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/uaraven/logview.(*LogView).distance(...)
	/Users/ovoronin/my/projects/logview/logview.go:1371
github.com/uaraven/logview.(*LogView).scrollOneDown(0xc00016a420)
	/Users/ovoronin/my/projects/logview/logview.go:1332 +0x6c
github.com/uaraven/logview.(*LogView).InputHandler.func1(0xc0004885e0, 0xc000e96780)
	/Users/ovoronin/my/projects/logview/logview.go:801 +0x3c9
```

**Comment by uaraven** [comment]
Seem to be fixed with the fixes for tailing
